### ISSUE TITLE
проблеми при збільшенні обсягів тексту

### ISSUE THREAD

**Issue by ipiwebtech** [digitaleinc/web-lab-1#1]
<img width="957" alt="overtexting" src="https://github.com/digitaleinc/web-lab-1/assets/129291207/58f9fb4a-c54f-4c59-b636-c3186ab994a9">
Додав більше тексту в центральний блок, і отримав розповзання по висоті шапки і плашки над центральним блоком. На додачу ще й горизонтальна смуга прокрутки появилася в сторінки. Все позначив червоним маркером.

**Comment by digitaleinc** [comment]
Resolved issues
